### ISSUE TITLE
vue files must be strongly typed

### ISSUE THREAD

**Issue by bezrukovyura** [CopyTranslator/CopyTranslator#52] opened 2019-03-04 01:47 UTC
Example
```

<template>...</template>

<script lang="ts">
  import { Controller } from '../controller';
  import Vue from 'vue';
  import Component from 'vue-class-component'
  import { TreeElementsResponsVue, ExportResponse, JournalLastMeteringsPrepare } from '../model';
  import moment from 'moment';

  @Component({
    props: {
      model: {}
    }
  })

  export default class vue_table_mapping extends Vue {

    model: {
      controller: Controller,
      treeData: TreeElementsResponsVue,
      activeTreeElement: (
        x: number[],
        callBack: () => void
      ) => void
    };

    showProgress = false;
    tableMapsOld: ExportResponse[] = [];
    tableMaps: ExportResponse[] = [];
    loadJournal: JournalLastMeteringsPrepare[] = [];
    timeZone: number = 0;

    get existData() {
      return this.tableMaps.length && this.tableMaps.length > 0;
    }

    created() {
      this.$parent.$on('applyExportSetting', this.refresh_mapping);
      this.refresh_mapping();
    }

    apply() {
      this.showProgress = true;

      this.model.controller.exportApplyFromMapping(this.tableMaps, this.model.treeData, (x) => {
        this.showProgress = false;
        this.refresh_mapping();
      });
    }

    refresh_mapping() {
      this.showProgress = true;
      this.model.controller.mappingTable.get().then(x => {
        this.tableMaps = x;
        this.tableMapsOld = JSON.parse(JSON.stringify(x));
        this.showProgress = false;
        this.refresh_journal();
      });
    }

  }

</script>

<style scoped>...</style>
```

good luck with your work)

**Comment by elliottzheng** [comment] 2019-03-04 01:57
Thank you for your advice, I will reformat the vue files with ts.

**Comment by fairol85** [comment] 2019-08-24 03:10
Duplicate of #

**Closed** 2019-10-18 04:40 UTC
Labels: enhancement
